# THis file contains services and things that are run in both production & development env
version: "3.9"

services:

  db: 
    image: postgres
    restart: always 
    environment:
      POSTGRES_USER: ${PSQL_USER} 
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}