# dev override file
version: "3.9"

services:
  # Postgres database
  db:
    ports: # Expose ports so that apps not running via docker compose can connect to them.
      - 5432:5432 # format here is "port on our machine":"port on container"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula 
    ports:
      - 3333:8080
  
  tailwind:
    build:
    # use the dockerfile located in tailwind dir for building the service
      context: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    # the use of volumes in the Docker Compose file allows changes made on our local machine to be reflected inside the container without rebuilding the images.
    # mounts local directories into the container. Thsi is bi-directional. So any changes inside local computer or container will synchronize.
    volumes:
    - ./tailwind:/src
    - ./assets:/dst
    - ./templates:/templates