version: "3.9"

x-logging:
  &highlight-logging
    driver: fluentd
    options:
        fluentd-address: "otel.highlight.io:24224"
        fluentd-async: "true"
        fluentd-sub-second-precision: "true"
        tag: "highlight.project_id=memopvyd"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /home/ubuntu/data/lenspix.com/images:/images 
    # ports: # for testing only
    #   - 3000:3000
    depends_on:
      - db
    logging: *highlight-logging

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging: *highlight-logging

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER} 
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - /home/ubuntu/data/lenspix.com/psql:/var/lib/postgresql/data/pgdata
    logging: *highlight-logging
